language: python
python:
  - "3.8"
cache: pip
install:
  - python setup.py develop
  - pip install --upgrade --upgrade-strategy eager -r dev-requirements.txt -e .
  #- pip uninstall qiskit
  #- pip install qiskit ase  numpy>=1.18.5 scipy>=1.4.1 matplotlib>=3.0.0 phonopy==2.8.1 coverage lightgbm==2.1.0  flask joblib networkx tqdm dgl scikit-learn pandas pennylane codecov torch keras tensorflow==2.3.0  pytest pytest-cov bokeh
  #- pip install -r requirements-for-ci-only.txt
  #- pip install git+https://github.com/aspuru-guzik-group/tequila.git
  #- pip install git+https://github.com/aspuru-guzik-group/tequila.git@402d8eb8c4c632c2d48c75e2f798a46967d28899
  #- python setup.py develop
script:
  - coverage run -m pytest
  - coverage report -m
