name: JARVIS-Tools github action

on: [push, pull_request]

jobs:
  build:
    name: build jarvis-tools
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip   
        python setup.py develop
        pip install qiskit
    - name: Test with pytest
      run: |
        python -m pip install --upgrade pip   
        pip install qiskit
        python setup.py install

        pip install numpy==1.18.5 scipy==1.4.1 matplotlib>=3.0.0 phonopy==2.8.1 coverage lightgbm==2.1.0  flask joblib networkx scikit-learn pandas pennylane==0.13.0   qiskit==0.16.2 codecov torch==1.5.1 keras tensorflow==2.3.0  pytest pytest-cov bokeh
        #pip install -r requirements-ci.txt
        
        
        #git clone https://github.com/Qiskit/qiskit.git
        #cd qiskit
        #python setup.py install
        
        
        #cd ..
        coverage run -m pytest
        coverage report -m
        codecov
        codecov --token="b61081a0-39de-44a8-8a9c-97d4be82af6d"
        # git clone https://github.com/QEF/q-e.git
        # cd q-e
        # ./configure
        # make pw
            
